export * from '@/core/main';

import {
    animateHeight,
    animateOpacity,
    disableScroll,
    easeInOutQuad,
    enableScroll,
    fadeIn,
    fadeOut,
    getDocumentScrollLeft,
    getDocumentScrollTop,
    getFullHeight,
    getScrollPosition,
    getViewportScrollLeft,
    getViewportScrollTop,
    isElementVisible,
    scrollToBottom as toBottom,
    scrollToElement as toElement,
    scrollToPosition as toPosition,
    scrollToTop as toTop,
    slideDown,
    slideToggle,
    slideUp,
    smoothScrollToElement as smoothToElement,
    smoothScrollToPosition as smoothToPosition,
    smoothScrollToTop as smoothToTop,
    toggleClassOnScroll,
} from '@/core/main';

const Scroll = {
    animateHeight,
    animateOpacity,
    disableScroll,
    easeInOutQuad,
    enableScroll,
    fadeIn,
    fadeOut,
    getDocumentScrollLeft,
    getDocumentScrollTop,
    getFullHeight,
    getScrollPosition,
    getViewportScrollLeft,
    getViewportScrollTop,
    isElementVisible,
    toBottom,
    toElement,
    toPosition,
    toTop,
    slideDown,
    slideToggle,
    slideUp,
    smoothToElement,
    smoothToPosition,
    smoothToTop,
    toggleClassOnScroll,
};

export default Scroll;
